import React, { useState } from 'react';
import { Presentation, Copy, CheckCircle2, Download, FileText } from 'lucide-react';
import { cn } from '../lib/utils';
import { CardSkeleton } from './CardSkeleton';
import pptxgen from 'pptxgenjs';

export const PresentationCard = ({ data, isGenerating, staggerDelay, eventNameBrief }) => {
  const [copied, setCopied] = useState(false);

  const showSkeleton = isGenerating || !data?.slides;

  const getFullText = () => {
    if (!data?.slides) return '';
    return data.slides.map((s, i) => `Slide ${i + 1}: ${s.title}\n${s.bullets.map(b => '- ' + b).join('\n')}`).join('\n\n');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getFullText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportText = () => {
    const text = getFullText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'presentation_outline.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPptx = () => {
    if (!data?.slides) return;
    
    let pptx = new pptxgen();
    pptx.layout = 'LAYOUT_16x9';

    // Slide 1: Title Slide
    let slide1 = pptx.addSlide();
    slide1.background = { color: '1a1a1f' };
    slide1.addShape(pptx.ShapeType.rect, { 
      x: 0, y: 0, w: '25%', h: '100%', fill: { color: '4f8ef7' } 
    });
    slide1.addText(data.slides[0]?.title || "Event Presentation", {
      x: '28%', y: '40%', w: '65%', h: 1.5,
      color: 'FFFFFF', bold: true, fontSize: 44, fontFace: 'Arial'
    });
    slide1.addText("Generated by ClubOS", {
      x: '28%', y: '60%', w: '65%', h: 1,
      color: '4f8ef7', fontFace: 'Calibri', fontSize: 24, italic: true
    });

    // Slides 2-7: Content
    for (let i = 1; i < Math.min(data.slides.length - 1, 7); i++) {
       let contentSlide = pptx.addSlide();
       contentSlide.background = { color: '1a1a1f' };
       
       // Header
       contentSlide.addText(data.slides[i].title, {
         x: 0.5, y: 0.5, w: '80%', h: 1,
         color: '4f8ef7', bold: true, fontSize: 32, fontFace: 'Arial'
       });
       
       // Logo Placeholder
       contentSlide.addShape(pptx.ShapeType.rect, {
         x: '85%', y: 0.4, w: 1.2, h: 0.8, fill: { color: 'cccccc' }
       });
       contentSlide.addText("Club Logo", {
         x: '85%', y: 0.4, w: 1.2, h: 0.8,
         color: '000000', fontSize: 10, align: 'center', valign: 'middle'
       });

       // Bullets
       const bullets = data.slides[i].bullets.map(b => ({ text: b, options: { bullet: true } }));
       contentSlide.addText(bullets, {
         x: 0.8, y: 1.8, w: '85%', h: 4,
         color: 'FFFFFF', fontSize: 20, fontFace: 'Calibri', valign: 'top'
       });

       // Slide Number
       contentSlide.addText(String(i + 1), {
         x: '90%', y: '90%', w: 0.8, h: 0.5,
         color: '666666', fontSize: 14, align: 'right'
       });
    }

    // Slide 8: Thank you
    let lastData = data.slides[data.slides.length - 1];
    let slideN = pptx.addSlide();
    slideN.background = { color: '1a1a1f' };
    slideN.addText("Thank You", {
      x: 0, y: '40%', w: '100%', h: 1.5,
      color: '4f8ef7', bold: true, fontSize: 54, align: 'center', fontFace: 'Arial'
    });
    slideN.addText(lastData?.title || "Join us!", {
      x: 0, y: '60%', w: '100%', h: 1,
      color: 'FFFFFF', fontSize: 28, align: 'center', fontFace: 'Calibri'
    });

    const fileName = `ClubOS_${eventNameBrief || 'Presentation'}.pptx`;
    pptx.writeFile({ fileName });
  };

  return (
    <div className={cn("bg-card border border-[#2a2a33] rounded-2xl p-6 transition-all duration-700 shadow-lg flex flex-col h-[28rem] relative overflow-hidden slide-up-card group", isGenerating && "border-accent/50 shadow-[0_0_15px_rgba(79,142,247,0.15)]")} style={{ animationDelay: `${staggerDelay}ms`, animationFillMode: 'both' }}>
      {isGenerating && <div className="absolute inset-0 border-2 border-transparent rounded-2xl bg-gradient-to-r from-accent via-indigo-500 to-accent opacity-20 animate-[shimmer_2s_linear_infinite] pointer-events-none bg-[length:200%_auto]" style={{ maskImage: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)', maskComposite: 'exclude', padding: '1px' }}></div>}

      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3 text-accent relative">
          {isGenerating && <span className="absolute -inset-2 bg-accent/20 rounded-full blur-xl animate-pulse"></span>}
          <div className="p-2 bg-accent/10 rounded-xl relative border border-accent/20">
            <Presentation size={20} className={isGenerating ? 'animate-pulse' : ''} />
          </div>
          <h3 className="font-semibold text-gray-100 text-lg tracking-wide">Presentation</h3>
        </div>
        {!showSkeleton && (
          <div className="flex gap-2">
            <button onClick={handleExportText} className="text-gray-400 hover:text-white transition-colors p-2 rounded-lg bg-[#2a2a33]/50 hover:bg-[#2a2a33]/80 flex items-center gap-2 text-xs font-semibold shadow-sm" title="Download Text">
              <FileText size={14} /> .txt
            </button>
            <button onClick={handleDownloadPptx} className="text-white transition-colors p-2 rounded-lg bg-accent/20 hover:bg-accent border border-accent/40 hover:shadow-[0_0_15px_rgba(79,142,247,0.4)] flex items-center gap-2 text-xs font-semibold" title="Download PPTX">
              <Download size={14} /> .pptx
            </button>
          </div>
        )}
      </div>

      <div className="flex-1 overflow-y-auto custom-scrollbar bg-[#121215] rounded-xl border border-[#2a2a33]/50 p-4 relative z-0 flex flex-col">
        {showSkeleton ? (
           <CardSkeleton />
        ) : (
          <div className="flex flex-col gap-6 relative">
            {data.slides.map((slide, idx) => (
              <div key={idx} className="relative flex gap-4 pr-2">
                <div className="text-4xl font-black text-[#2a2a33]/60 select-none tabular-nums tracking-tighter">{String(idx + 1).padStart(2, '0')}</div>
                <div className="pt-1">
                  <h4 className="font-bold text-gray-200 text-sm mb-2 leading-tight">{slide.title}</h4>
                  <ul className="space-y-1">
                    {slide.bullets.map((bullet, bIdx) => (
                      <li key={bIdx} className="text-xs text-gray-400 relative pl-4 leading-relaxed">
                        <span className="absolute left-0 top-1.5 w-1 h-1 rounded-full bg-accent/60"></span>
                        {bullet}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
            
            <div className="mt-4 pt-4 border-t border-[#2a2a33] flex justify-center pb-2">
              <button onClick={handleCopy} className="text-gray-300 hover:text-white flex items-center gap-2 bg-[#2a2a33]/40 px-4 py-2 rounded-lg transition font-medium text-sm hover:shadow-lg">
                {copied ? <CheckCircle2 size={16} className="text-green-400" /> : <Copy size={16} />}
                {copied ? "Copied All!" : "Copy All Slides"}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
